<?php
class Alumno extends Persona
{
    private int $numClases;
    public function __construct(string $nombre, string $apellidos, string $numTelefono)
    {
        parent::__construct($nombre, $apellidos, $numTelefono);
    }

    public function setNumClases(int $numClases): void
    {
        $this->numClases = $numClases;
    }

    public function aPagar() {
        if ($this->numClases == 1){
            echo "Importe a pagar 1 actividad: 20€";
        }
        elseif ($this->numClases == 2){
            echo "Importe a pagar 2 actividades: 32€";
        }
        elseif ($this->numClases >= 3){
            echo "Importe a pagar 3 o más actividades : 40€";
        }
        else echo "Debe indicar previamente el número de clases";
    }

    public function verInformacion()
    {
        parent::verInformacion(); // TODO: Change the autogenerated stub
    }

    public function getNombre(): string
    {
        return parent::getNombre(); // TODO: Change the autogenerated stub
    }

    public function setNombre(string $nombre): void
    {
        parent::setNombre($nombre); // TODO: Change the autogenerated stub
    }

    public function getApellidos(): string
    {
        return parent::getApellidos(); // TODO: Change the autogenerated stub
    }

    public function setApellidos(string $apellidos): void
    {
        parent::setApellidos($apellidos); // TODO: Change the autogenerated stub
    }

    public function getNumTelefono(): string
    {
        return parent::getNumTelefono(); // TODO: Change the autogenerated stub
    }

    public function setNumTelefono(string $numTelefono): void
    {
        parent::setNumTelefono($numTelefono); // TODO: Change the autogenerated stub
    }


}