<?php
class Profesor extends Persona
{
    const IMPORTE_POR_DEFECTO = 16;
    private string $nif;
    private $bailes = [];

    public function __construct(string $nombre, string $apellidos, string $numTelefono, string $nif) {
        parent::__construct($nombre, $apellidos, $numTelefono);
        $this->nif = $nif;
    }

    public function verInformacion()
    {
        parent::verInformacion(); // TODO: Change the autogenerated stub
    }

    public function getNombre(): string
    {
        return parent::getNombre(); // TODO: Change the autogenerated stub
    }

    public function setNombre(string $nombre): void
    {
        parent::setNombre($nombre); // TODO: Change the autogenerated stub
    }

    public function getApellidos(): string
    {
        return parent::getApellidos(); // TODO: Change the autogenerated stub
    }

    public function setApellidos(string $apellidos): void
    {
        parent::setApellidos($apellidos); // TODO: Change the autogenerated stub
    }

    public function getNumTelefono(): string
    {
        return parent::getNumTelefono(); // TODO: Change the autogenerated stub
    }

    public function setNumTelefono(string $numTelefono): void
    {
        parent::setNumTelefono($numTelefono); // TODO: Change the autogenerated stub
    }

    public function getNif(): string
    {
        return $this->nif;
    }

    public function setNif(string $nif): void
    {
        $this->nif = $nif;
    }



}